[build]
command = "python -m pip install -r requirements.txt && python -m streamlit run src/dashboard.py"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/"
status = 200

[build.packages]
python-dev = "3.11" 
