[build]
command = "pip install -r requirements.txt && streamlit run src/dashboard.py"
publish = "."

[build.environment]
PYTHON_VERSION = "3.11.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.packages]
python-dev = "3.11" 